### ISSUE TITLE
Improve Functionality of QuadChart Script

### ISSUE THREAD

**Issue by CarsonDavis** [CherrelleTucker/snwg-automation#3]
### Description

The QuadChart script is currently not entirely functional. We want to add the ability to pull in current and previous agendas.

### Implementation Considerations

- how do we select the folder in which the agendas are located?
    - use a folder id? is there a more general way, like identifying folders that say agenda?
- how to identify which agenda is from last week and this week?
   - function to see today's date? then calculate a possible date ranges?
- can we use the same function to find agenda, but give it a different date range when we want this week vs last week?
- how will we generate the hyperlink inside the table

### Deliverable

- [x] pull in current week agendas
- [x] pull in previous week agendas
- [x] format them nicely in the fake tables with hyperlinks

### Dependencies

depends on nothing

**Comment by CherrelleTucker** [comment]
https://github.com/CherrelleTucker/snwg-automation/blob/f2d39515c25ac014fe8fd206995ef3c7b451b1a4/newQuadChartSlide
